#!/bin/bash

# install py packages
pipenv install

# sync with pipfile.lock if need be
python ./rr-notifications/manage.py migrate

# cd into app
cd ./rr-notifications

# build dependent dirs
mkdir logs

# run dev server on localhost:8000
cd ..
./run
