# Generated by Django 2.0.5 on 2018-05-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Active Zip Code'),
        ),
    ]
