# Generated by Django 2.0.5 on 2018-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180520_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='opted_in',
            field=models.BooleanField(default=True, verbose_name='Account opted out of texts'),
        ),
    ]
